//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bag_imports_uk
    {
        public long id { get; set; }
        public decimal kg_from { get; set; }
        public Nullable<decimal> kg_to { get; set; }
        public decimal zone1 { get; set; }
        public decimal zone2 { get; set; }
        public decimal zone3 { get; set; }
        public decimal zone4 { get; set; }
        public decimal zone5 { get; set; }
        public decimal zone6 { get; set; }
        public decimal zone7 { get; set; }
        public decimal zone8 { get; set; }
        public decimal zone9 { get; set; }
        public decimal zone10 { get; set; }
        public Nullable<int> company { get; set; }
    }
}
