//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bag_c2c
    {
        public long id { get; set; }
        public decimal kg_from { get; set; }
        public Nullable<decimal> kg_to { get; set; }
        public string zone { get; set; }
        public decimal rate { get; set; }
        public Nullable<int> company { get; set; }
    }
}
