//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class source
    {
        public int id { get; set; }
        public string sr_code { get; set; }
        public string sr_name { get; set; }
        public string sr_usage { get; set; }
        public string sr_apc { get; set; }
        public string sr_branch { get; set; }
        public string sr_division { get; set; }
        public string sr_type { get; set; }
        public short sr_web { get; set; }
        public string sr_apcompany { get; set; }
        public string sr_category { get; set; }
        public string sr_urlre { get; set; }
        public byte[] sr_logo { get; set; }
        public string sr_agenturl { get; set; }
        public string sr_bccemail { get; set; }
        public string sr_surname { get; set; }
        public string sr_title { get; set; }
        public string sr_salutation { get; set; }
        public string sr_firstname { get; set; }
        public string sr_initials { get; set; }
        public string sr_addr1 { get; set; }
        public string sr_addr2 { get; set; }
        public string sr_addr3 { get; set; }
        public string sr_addr4 { get; set; }
        public string sr_postcode { get; set; }
        public string sr_region { get; set; }
        public string sr_tel_home { get; set; }
        public string sr_tel_work { get; set; }
        public string sr_mobile { get; set; }
        public string sr_fax { get; set; }
        public string sr_email { get; set; }
        public string sr_company { get; set; }
        public System.DateTime edited { get; set; }
        public string editedby { get; set; }
        public System.DateTime created { get; set; }
        public string createdby { get; set; }
    }
}
