//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FailedXML
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Path { get; set; }
        public string Status { get; set; }
        public string NavisionStatus { get; set; }
        public string QuoteType { get; set; }
    }
}
