//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMSLog
    {
        public long Id { get; set; }
        public string QuoteId { get; set; }
        public string Direction { get; set; }
        public string SMSText { get; set; }
        public Nullable<System.DateTime> CratedDate { get; set; }
    }
}
