//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class agents
    {
        public string a_code { get; set; }
        public string a_company { get; set; }
        public string a_addr1 { get; set; }
        public string a_addr2 { get; set; }
        public string a_addr3 { get; set; }
        public string a_addr4 { get; set; }
        public string a_postcode { get; set; }
        public string a_country { get; set; }
        public string a_tel { get; set; }
        public string a_fax { get; set; }
        public string a_email { get; set; }
        public string a_surname { get; set; }
        public string a_firstname { get; set; }
        public string a_initials { get; set; }
        public string a_titlle { get; set; }
        public string a_salutation { get; set; }
        public decimal a_sto_rate_f { get; set; }
        public decimal a_sto_hand_f { get; set; }
        public decimal a_sto_rate_g { get; set; }
        public decimal a_sto_hand_g { get; set; }
        public string a_paddr { get; set; }
        public string a_portcode { get; set; }
        public string a_notes { get; set; }
    }
}
