//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class air_rates
    {
        public long id { get; set; }
        public long rates_destinations_id { get; set; }
        public decimal airMin { get; set; }
        public decimal airlt50kg { get; set; }
        public decimal airlt100kg { get; set; }
        public decimal airlt150kg { get; set; }
        public decimal airlt200kg { get; set; }
        public decimal airlt300kg { get; set; }
        public decimal airover300kg { get; set; }
        public decimal doorMin { get; set; }
        public decimal door25plus { get; set; }
        public decimal door50plus { get; set; }
        public decimal door100plus { get; set; }
        public decimal door150plus { get; set; }
        public decimal door200plus { get; set; }
        public decimal door300plus { get; set; }
        public decimal handling { get; set; }
        public Nullable<int> company { get; set; }
    }
}
