//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_items
    {
        public long i_id { get; set; }
        public long i_quote_id { get; set; }
        public long i_carton_id { get; set; }
        public long i_enquiry_no { get; set; }
        public string i_type { get; set; }
        public string i_description { get; set; }
        public int i_length { get; set; }
        public int i_breadth { get; set; }
        public int i_height { get; set; }
        public int i_volume { get; set; }
        public int i_groweight { get; set; }
        public int i_quantity { get; set; }
    }
}
