//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_quotes
    {
        public long q_id { get; set; }
        public int q_enquiry_no { get; set; }
        public int q_quote_no { get; set; }
        public System.DateTime q_quote_dt { get; set; }
        public string q_origcity { get; set; }
        public string q_origcountry { get; set; }
        public string q_origcountry_code { get; set; }
        public string q_origpostcode { get; set; }
        public string q_destcity { get; set; }
        public string q_destcountry { get; set; }
        public string q_destcountry_code { get; set; }
        public string q_destination_code { get; set; }
        public decimal q_del_price { get; set; }
        public decimal q_col_price { get; set; }
        public int q_a_service_no { get; set; }
        public string q_shipsched { get; set; }
        public int q_groweight { get; set; }
        public int q_volume { get; set; }
        public int q_noItems { get; set; }
        public string q_pricenote { get; set; }
        public System.DateTime q_quote_email_sent { get; set; }
        public short q_is_alt_quote { get; set; }
        public short q_conversion_complete { get; set; }
        public long q_version { get; set; }
    }
}
