//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_services
    {
        public long s_id { get; set; }
        public int s_enquiry_no { get; set; }
        public long s_quote_id { get; set; }
        public long s_service_no { get; set; }
        public string s_type { get; set; }
        public string s_to { get; set; }
        public Nullable<int> s_vol_weight { get; set; }
        public string s_rate { get; set; }
        public Nullable<decimal> s_price { get; set; }
        public Nullable<System.DateTime> s_mw_copied { get; set; }
    }
}
