//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class baggage_visitors
    {
        public long id { get; set; }
        public string title { get; set; }
        public string firstName { get; set; }
        public string surName { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string orig_country { get; set; }
        public string orig_city { get; set; }
        public string orig_postcode { get; set; }
        public string dest_country { get; set; }
        public string dest_city { get; set; }
        public string dest_postcode { get; set; }
        public System.DateTime prop_collection_date { get; set; }
        public string source { get; set; }
        public string referrer { get; set; }
        public string company_id { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> response_sent { get; set; }
    }
}
