//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class baggage_new_move_date
    {
        public int e_enquiry_no { get; set; }
        public int q_quote_no { get; set; }
        public short e_lost { get; set; }
        public short e_accepted { get; set; }
        public string Quote_Date { get; set; }
        public string Proposed_Date { get; set; }
        public string New_Move_Date { get; set; }
    }
}
