//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class baggage
    {
        public int e_enquiry_no { get; set; }
        public System.DateTime e_enquiry_dt { get; set; }
        public Nullable<short> e_cutoff { get; set; }
        public string e_apcompany { get; set; }
        public string e_branch { get; set; }
        public string e_estimator { get; set; }
        public System.DateTime e_allocated { get; set; }
        public string e_source { get; set; }
        public string e_comments { get; set; }
        public string e_title { get; set; }
        public string e_surname { get; set; }
        public string e_firstname { get; set; }
        public string e_telephone { get; set; }
        public string e_email { get; set; }
        public short e_emailq { get; set; }
        public short e_lost { get; set; }
        public short e_accepted { get; set; }
        public string e_lost_to { get; set; }
        public string e_ap_number { get; set; }
        public System.DateTime e_adate { get; set; }
        public int e_a_quote_no { get; set; }
        public int e_h_quote_no { get; set; }
        public System.DateTime e_emailfu1 { get; set; }
        public System.DateTime e_emailfu2 { get; set; }
        public System.DateTime e_emailfu3 { get; set; }
        public System.DateTime e_emailfu4 { get; set; }
        public System.DateTime e_followup1 { get; set; }
        public System.DateTime e_followup2 { get; set; }
        public string e_notes { get; set; }
        public System.DateTime e_added { get; set; }
        public short e_taxinfo { get; set; }
        public System.DateTime e_taxinfo_email_sent { get; set; }
        public System.DateTime e_book_now_updated { get; set; }
        public short e_fxinfo { get; set; }
        public System.DateTime e_fxinfo_email_sent { get; set; }
        public short e_web { get; set; }
        public short e_internal { get; set; }
        public short e_referred { get; set; }
        public short e_needs_alt_quote { get; set; }
        public string e_search_info { get; set; }
        public System.DateTime e_prop_collection_date { get; set; }
        public long e_version { get; set; }
    }
}
