//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class corp
    {
        public string c_code { get; set; }
        public string c_company { get; set; }
        public string c_addr1 { get; set; }
        public string c_addr2 { get; set; }
        public string c_addr3 { get; set; }
        public string c_addr4 { get; set; }
        public string c_postcode { get; set; }
        public string c_tel { get; set; }
        public string c_fax { get; set; }
        public string c_email { get; set; }
        public string c_surname { get; set; }
        public string c_firstname { get; set; }
        public string c_initials { get; set; }
        public string c_title { get; set; }
        public string c_salutation { get; set; }
        public string c_position { get; set; }
        public string c_account_no { get; set; }
        public string c_paddr { get; set; }
        public string c_notes { get; set; }
    }
}
