//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class courier_rates
    {
        public long id { get; set; }
        public long zone { get; set; }
        public decimal weight { get; set; }
        public decimal rate { get; set; }
        public Nullable<int> company { get; set; }
    }
}
