//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customs_guides
    {
        public long id { get; set; }
        public string name { get; set; }
        public byte[] pdf { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<long> version { get; set; }
    }
}
