//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_collection_rates
    {
        public long id { get; set; }
        public long zone { get; set; }
        public decimal del_1st_item { get; set; }
        public decimal del_each_item { get; set; }
        public decimal del_minimum { get; set; }
        public decimal col_1st_item { get; set; }
        public decimal col_each_item { get; set; }
        public decimal col_minimum { get; set; }
        public string company { get; set; }
    }
}
