//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class edestinations
    {
        public int id { get; set; }
        public string programme { get; set; }
        public string description { get; set; }
        public string run_frequency { get; set; }
        public string tablename { get; set; }
        public string columnname { get; set; }
        public string apcompany { get; set; }
        public string selection { get; set; }
        public string emailto { get; set; }
        public string emailcc { get; set; }
        public string emailbcc { get; set; }
        public string emailfrom { get; set; }
        public string subject { get; set; }
        public string attachemnt { get; set; }
        public string content { get; set; }
        public decimal time { get; set; }
        public string frequency { get; set; }
        public string notes { get; set; }
    }
}
