//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_count
    {
        public short id { get; set; }
        public int tax_ap { get; set; }
        public int tax_1c { get; set; }
        public int fx_ap { get; set; }
        public int fx_ap_oz { get; set; }
        public int fx_1c { get; set; }
        public int fx { get; set; }
        public System.DateTime ts { get; set; }
    }
}
