//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string initials { get; set; }
        public string password { get; set; }
        public string surname { get; set; }
        public string forenames { get; set; }
        public System.DateTime dob { get; set; }
        public string security { get; set; }
        public string apcompany { get; set; }
        public string apcompany2 { get; set; }
        public string notes { get; set; }
    }
}
