//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estim
    {
        public string es_init { get; set; }
        public string es_name { get; set; }
        public string es_coordinator { get; set; }
        public string es_alias { get; set; }
        public string es_est_email { get; set; }
        public string es_coord_email { get; set; }
        public short es_active { get; set; }
        public string es_apcompany { get; set; }
    }
}
