//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fxenquiries
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string address { get; set; }
        public string destination { get; set; }
        public string departure { get; set; }
        public string value { get; set; }
        public string comments { get; set; }
        public System.DateTime dateCreated { get; set; }
        public int version { get; set; }
    }
}
