//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class guides
    {
        public int id { get; set; }
        public long countries_id { get; set; }
        public string baggage_url { get; set; }
        public string baggage_desc { get; set; }
        public string removals_url { get; set; }
        public string removals_desc { get; set; }
        public string cars_url { get; set; }
        public string cars_desc { get; set; }
        public System.DateTime ts { get; set; }
    
        public virtual countries countries { get; set; }
    }
}
