//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_agency_position
    {
        public int id { get; set; }
        public long agency_id { get; set; }
        public long position_id { get; set; }
    
        public virtual job_agency job_agency { get; set; }
        public virtual job_position job_position { get; set; }
    }
}
