//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public job_agency()
        {
            this.job_agency_city = new HashSet<job_agency_city>();
            this.job_agency_email_log = new HashSet<job_agency_email_log>();
            this.job_agency_position = new HashSet<job_agency_position>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string contact_name { get; set; }
        public string reporting_contact { get; set; }
        public string residency_type { get; set; }
        public short is_live { get; set; }
        public string notes { get; set; }
        public string amendedby { get; set; }
        public System.DateTime amended { get; set; }
        public string createdby { get; set; }
        public System.DateTime created { get; set; }
        public string email_address { get; set; }
        public string reporting_email { get; set; }
        public string bcc_reporting_email { get; set; }
        public string cc_contact_name { get; set; }
        public string cc_email_address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_agency_city> job_agency_city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_agency_email_log> job_agency_email_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_agency_position> job_agency_position { get; set; }
    }
}
