//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_agency_email_log
    {
        public int id { get; set; }
        public long agency_id { get; set; }
        public long registration_id { get; set; }
        public Nullable<System.DateTime> date_reported { get; set; }
    
        public virtual job_agency job_agency { get; set; }
        public virtual job_registrations job_registrations { get; set; }
    }
}
