//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class locinfo
    {
        public string li_apu { get; set; }
        public string li_apc { get; set; }
        public string li_apb { get; set; }
        public string li_apd { get; set; }
        public string li_apt { get; set; }
        public string li_name { get; set; }
        public string li_address { get; set; }
        public string li_email { get; set; }
        public string li_tel { get; set; }
        public string li_fax { get; set; }
    }
}
