//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class master
    {
        public string company { get; set; }
        public string a1 { get; set; }
        public string a2 { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string vatno { get; set; }
        public int next_bag { get; set; }
        public int next_rem { get; set; }
        public int next_tra { get; set; }
        public int next_veh { get; set; }
        public int first_bag { get; set; }
        public int first_rem { get; set; }
        public int first_tra { get; set; }
        public int first_veh { get; set; }
        public decimal vat1 { get; set; }
        public decimal vat2 { get; set; }
        public decimal vat3 { get; set; }
        public string acc_path { get; set; }
        public string acc_id { get; set; }
        public string acc_pw { get; set; }
        public string doc_dir { get; set; }
        public string data_ver { get; set; }
        public string PPP { get; set; }
    }
}
