//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class migration_events
    {
        public int id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string date { get; set; }
        public string url { get; set; }
        public System.DateTime lastupdate { get; set; }
    }
}
