//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthly_service_summary
    {
        public int id { get; set; }
        public long enquiry { get; set; }
        public string company { get; set; }
        public string website { get; set; }
        public System.DateTime e_date { get; set; }
        public string e_name { get; set; }
        public string country_code { get; set; }
        public string country { get; set; }
        public Nullable<byte> banking { get; set; }
        public Nullable<byte> cars { get; set; }
        public Nullable<byte> tax { get; set; }
        public Nullable<byte> pets { get; set; }
        public Nullable<byte> baggage { get; set; }
        public Nullable<byte> pensions { get; set; }
        public Nullable<byte> fx { get; set; }
        public System.DateTime last_updated { get; set; }
    }
}
