//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class opt_out
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public opt_out()
        {
            this.newsletter_category = new HashSet<newsletter_category>();
        }
    
        public long id { get; set; }
        public string email { get; set; }
        public string company_id { get; set; }
        public Nullable<short> all_categories { get; set; }
        public Nullable<System.DateTime> moveware_copied { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public long version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newsletter_category> newsletter_category { get; set; }
    }
}
