//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pages()
        {
            this.page_attributes = new HashSet<page_attributes>();
        }
    
        public long id { get; set; }
        public string site { get; set; }
        public string name { get; set; }
        public string content_type { get; set; }
        public string inherits { get; set; }
        public string template { get; set; }
        public System.DateTime last_updated { get; set; }
        public long version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<page_attributes> page_attributes { get; set; }
    }
}
