//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_log
    {
        public long id { get; set; }
        public string page { get; set; }
        public string method { get; set; }
        public string handler { get; set; }
        public string server { get; set; }
        public string remote_address { get; set; }
        public string session_id { get; set; }
        public string user_agent { get; set; }
        public System.DateTime log_date { get; set; }
    }
}
