//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_attributes
    {
        public long id { get; set; }
        public long page_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public int page_attributes_idx { get; set; }
        public string value { get; set; }
        public System.DateTime last_updated { get; set; }
        public long version { get; set; }
    
        public virtual pages pages { get; set; }
    }
}
