//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class porttype
    {
        public string ps_port { get; set; }
        public string ps_type { get; set; }
        public string ps_weeks { get; set; }
        public string ps_days { get; set; }
        public string ps_agent { get; set; }
        public string ps_company { get; set; }
        public string ps_next_vessel { get; set; }
        public System.DateTime ps_next_loading { get; set; }
        public System.DateTime ps_next_eta { get; set; }
    }
}
