//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class port
    {
        public string pt_code { get; set; }
        public string pt_name { get; set; }
        public string pt_city { get; set; }
        public string pt_ctrycode { get; set; }
        public string pt_country { get; set; }
        public string pt_wzone { get; set; }
        public string pt_currency { get; set; }
    }
}
