//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prop_agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prop_agency()
        {
            this.prop_agency_city = new HashSet<prop_agency_city>();
            this.prop_agency_email_log = new HashSet<prop_agency_email_log>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string contact_name { get; set; }
        public string contact_email { get; set; }
        public string cc_name { get; set; }
        public string cc_email { get; set; }
        public string reporting_name { get; set; }
        public string reporting_email { get; set; }
        public string reporting_bcc { get; set; }
        public short is_live { get; set; }
        public string notes { get; set; }
        public string createdby { get; set; }
        public System.DateTime created { get; set; }
        public string amendedby { get; set; }
        public System.DateTime amended { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prop_agency_city> prop_agency_city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prop_agency_email_log> prop_agency_email_log { get; set; }
    }
}
