//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prop_registrations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prop_registrations()
        {
            this.prop_agency_email_log = new HashSet<prop_agency_email_log>();
        }
    
        public long id { get; set; }
        public string forename { get; set; }
        public string surname { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string city { get; set; }
        public string county { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public System.DateTime arrival_date { get; set; }
        public string special_requirements { get; set; }
        public string additional_information { get; set; }
        public long prop_country { get; set; }
        public Nullable<long> prop_area { get; set; }
        public Nullable<long> prop_city { get; set; }
        public string prop_suburb { get; set; }
        public string prop_type { get; set; }
        public short prop_bedrooms { get; set; }
        public string prop_price_range { get; set; }
        public string prop_currency { get; set; }
        public short info_baggage_shipping { get; set; }
        public short info_banking_downunder { get; set; }
        public short info_car_shipping { get; set; }
        public short info_international_removals { get; set; }
        public short info_jobs_downunder { get; set; }
        public short info_migrant_airfares { get; set; }
        public short info_money_transfers { get; set; }
        public short info_pet_transportation { get; set; }
        public short info_uk_tax_rebates { get; set; }
        public short info_pension_transfers { get; set; }
        public short info_offshore_investments { get; set; }
        public short info_emigration_visas { get; set; }
        public Nullable<System.DateTime> received { get; set; }
        public Nullable<System.DateTime> registrant_email_sent { get; set; }
        public Nullable<System.DateTime> agency_email_sent { get; set; }
        public Nullable<System.DateTime> followup_email_sent { get; set; }
    
        public virtual carea carea { get; set; }
        public virtual city city1 { get; set; }
        public virtual countries countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prop_agency_email_log> prop_agency_email_log { get; set; }
    }
}
