//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prop_visitors
    {
        public long id { get; set; }
        public string email { get; set; }
        public long country_id { get; set; }
        public string source { get; set; }
        public string referrer { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> response_sent { get; set; }
    
        public virtual countries countries { get; set; }
    }
}
