//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using QuoteCalculator.Service.Models;
    using QuoteCalculator.Service.Helper;
    using System.Configuration;

    public partial class quotesEntities : DbContext
    {
        static string _connection = EFConnection.EFConnectionString;
        public quotesEntities()
            : base(_connection)
        {
        }

        //public quotesEntities() : base(AESEncryptionDecryptionHelper.Decrypt(ConfigurationManager.ConnectionStrings["quotesEntities"].ToString()))
        //{
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_EmailTemplate> tbl_EmailTemplate { get; set; }
        public virtual DbSet<tbl_ExcelSheetName> tbl_ExcelSheetName { get; set; }
        public virtual DbSet<tbl_PostCodeUK> tbl_PostCodeUK { get; set; }
        public virtual DbSet<tbl_Quote> tbl_Quote { get; set; }
        public virtual DbSet<tbl_Service> tbl_Service { get; set; }
        public virtual DbSet<tbl_VehicleMake> tbl_VehicleMake { get; set; }
        public virtual DbSet<tbl_VehicleModel> tbl_VehicleModel { get; set; }
        public virtual DbSet<tbl_VehicleType> tbl_VehicleType { get; set; }
        public virtual DbSet<agents> agents { get; set; }
        public virtual DbSet<b_items> b_items { get; set; }
        public virtual DbSet<b_quotes> b_quotes { get; set; }
        public virtual DbSet<b_services> b_services { get; set; }
        public virtual DbSet<baggage> baggage { get; set; }
        public virtual DbSet<baggage_visitors> baggage_visitors { get; set; }
        public virtual DbSet<baglines> baglines { get; set; }
        public virtual DbSet<bankingenquiries> bankingenquiries { get; set; }
        public virtual DbSet<branch> branch { get; set; }
        public virtual DbSet<carea> carea { get; set; }
        public virtual DbSet<cartons> cartons { get; set; }
        public virtual DbSet<cartons_old> cartons_old { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<compets> compets { get; set; }
        public virtual DbSet<corp> corp { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<countries_iso> countries_iso { get; set; }
        public virtual DbSet<currency_rate> currency_rate { get; set; }
        public virtual DbSet<customs_guides> customs_guides { get; set; }
        public virtual DbSet<delivery_collection_rates> delivery_collection_rates { get; set; }
        public virtual DbSet<division> division { get; set; }
        public virtual DbSet<edestinations> edestinations { get; set; }
        public virtual DbSet<email_count> email_count { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<estim> estim { get; set; }
        public virtual DbSet<fxenquiries> fxenquiries { get; set; }
        public virtual DbSet<guides> guides { get; set; }
        public virtual DbSet<inserts> inserts { get; set; }
        public virtual DbSet<job_agency> job_agency { get; set; }
        public virtual DbSet<job_agency_city> job_agency_city { get; set; }
        public virtual DbSet<job_agency_email_log> job_agency_email_log { get; set; }
        public virtual DbSet<job_agency_position> job_agency_position { get; set; }
        public virtual DbSet<job_industry> job_industry { get; set; }
        public virtual DbSet<job_position> job_position { get; set; }
        public virtual DbSet<job_registrations> job_registrations { get; set; }
        public virtual DbSet<job_registrations_documents> job_registrations_documents { get; set; }
        public virtual DbSet<job_residence> job_residence { get; set; }
        public virtual DbSet<job_type> job_type { get; set; }
        public virtual DbSet<job_visitors> job_visitors { get; set; }
        public virtual DbSet<letters> letters { get; set; }
        public virtual DbSet<locinfo> locinfo { get; set; }
        public virtual DbSet<migration_events> migration_events { get; set; }
        public virtual DbSet<monthly_service_summary> monthly_service_summary { get; set; }
        public virtual DbSet<movable_item> movable_item { get; set; }
        public virtual DbSet<movable_item_room_code> movable_item_room_code { get; set; }
        public virtual DbSet<newsletter_article> newsletter_article { get; set; }
        public virtual DbSet<newsletter_category> newsletter_category { get; set; }
        public virtual DbSet<opt_out> opt_out { get; set; }
        public virtual DbSet<page_attribute_dictionary> page_attribute_dictionary { get; set; }
        public virtual DbSet<page_attributes> page_attributes { get; set; }
        public virtual DbSet<page_log> page_log { get; set; }
        public virtual DbSet<pages> pages { get; set; }
        public virtual DbSet<port> port { get; set; }
        public virtual DbSet<ports> ports { get; set; }
        public virtual DbSet<porttype> porttype { get; set; }
        public virtual DbSet<prohibited_email> prohibited_email { get; set; }
        public virtual DbSet<prop_agency> prop_agency { get; set; }
        public virtual DbSet<prop_agency_city> prop_agency_city { get; set; }
        public virtual DbSet<prop_agency_email_log> prop_agency_email_log { get; set; }
        public virtual DbSet<prop_registrations> prop_registrations { get; set; }
        public virtual DbSet<prop_visitors> prop_visitors { get; set; }
        public virtual DbSet<propcoll> propcoll { get; set; }
        public virtual DbSet<r_quotes> r_quotes { get; set; }
        public virtual DbSet<radius> radius { get; set; }
        public virtual DbSet<referrers> referrers { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<registration_code> registration_code { get; set; }
        public virtual DbSet<removal_ORIG> removal_ORIG { get; set; }
        public virtual DbSet<removal_services> removal_services { get; set; }
        public virtual DbSet<removals_inventory_document> removals_inventory_document { get; set; }
        public virtual DbSet<review> review { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<room_type> room_type { get; set; }
        public virtual DbSet<room_type_default_room_name> room_type_default_room_name { get; set; }
        public virtual DbSet<sailingsched> sailingsched { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<shipments> shipments { get; set; }
        public virtual DbSet<sites> sites { get; set; }
        public virtual DbSet<sms_chat> sms_chat { get; set; }
        public virtual DbSet<sms_message> sms_message { get; set; }
        public virtual DbSet<sms_message_chat> sms_message_chat { get; set; }
        public virtual DbSet<source> source { get; set; }
        public virtual DbSet<static_resources> static_resources { get; set; }
        public virtual DbSet<t_quotes> t_quotes { get; set; }
        public virtual DbSet<trade> trade { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<uk> uk { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<v_quotes> v_quotes { get; set; }
        public virtual DbSet<vehicle> vehicle { get; set; }
        public virtual DbSet<vehicle_make> vehicle_make { get; set; }
        public virtual DbSet<vehicle_model> vehicle_model { get; set; }
        public virtual DbSet<velocity_templates> velocity_templates { get; set; }
        public virtual DbSet<world_zones> world_zones { get; set; }
        public virtual DbSet<wzone> wzone { get; set; }
        public virtual DbSet<baggage_new_move_date> baggage_new_move_date { get; set; }
        public virtual DbSet<countries_dhl> countries_dhl { get; set; }
        public virtual DbSet<master> master { get; set; }
        public virtual DbSet<smailmge> smailmge { get; set; }
        public virtual DbSet<tbl_VehicleModelList> tbl_VehicleModelList { get; set; }
        public virtual DbSet<tbl_AdditionalQuickQuoteItems> tbl_AdditionalQuickQuoteItems { get; set; }
        public virtual DbSet<tbl_InternationalRemoval> tbl_InternationalRemoval { get; set; }
        public virtual DbSet<tbl_QuickQuoteItems> tbl_QuickQuoteItems { get; set; }
        public virtual DbSet<tbl_Vehicle> tbl_Vehicle { get; set; }
        public virtual DbSet<tbl_Menu> tbl_Menu { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_RoleMenuMap> tbl_RoleMenuMap { get; set; }
        public virtual DbSet<tbl_AccessCode> tbl_AccessCode { get; set; }
        public virtual DbSet<tbl_QuoteType> tbl_QuoteType { get; set; }
        public virtual DbSet<tbl_TransitionTimeLine> tbl_TransitionTimeLine { get; set; }
        public virtual DbSet<tbl_ChildContent> tbl_ChildContent { get; set; }
        public virtual DbSet<tbl_CreditorProducts> tbl_CreditorProducts { get; set; }
        public virtual DbSet<tbl_CreditorProducts_Rate> tbl_CreditorProducts_Rate { get; set; }
        public virtual DbSet<tbl_OptOut> tbl_OptOut { get; set; }
        public virtual DbSet<tbl_QuoteAmount> tbl_QuoteAmount { get; set; }
        public virtual DbSet<branch_postcode> branch_postcode { get; set; }
        public virtual DbSet<tbl_Company> tbl_Company { get; set; }
        public virtual DbSet<rates_destinations> rates_destinations { get; set; }
        public virtual DbSet<air_rates> air_rates { get; set; }
        public virtual DbSet<bag_c2c> bag_c2c { get; set; }
        public virtual DbSet<bag_imports_uk> bag_imports_uk { get; set; }
        public virtual DbSet<courier_rates> courier_rates { get; set; }
        public virtual DbSet<matrix_c2c> matrix_c2c { get; set; }
        public virtual DbSet<sea_rates> sea_rates { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<tbl_VehicleShippingRates> tbl_VehicleShippingRates { get; set; }
        public virtual DbSet<tbl_FailedXML> tbl_FailedXML { get; set; }
        public virtual DbSet<tbl_DaySchedule> tbl_DaySchedule { get; set; }
        public virtual DbSet<tbl_BaggageItem> tbl_BaggageItem { get; set; }
        public virtual DbSet<road_rates> road_rates { get; set; }
        public virtual DbSet<tbl_SMSLog> tbl_SMSLog { get; set; }
        public virtual DbSet<tbl_Title> tbl_Title { get; set; }
        public virtual DbSet<express_courier_rates> express_courier_rates { get; set; }
        public virtual DbSet<tbl_baggageQuote> tbl_baggageQuote { get; set; }
        public virtual DbSet<tbl_HeadingContent> tbl_HeadingContent { get; set; }
        public virtual DbSet<tbl_CountryCode> tbl_CountryCode { get; set; }
        public virtual DbSet<tbl_CommonSettings> tbl_CommonSettings { get; set; }
        public virtual DbSet<tbl_GuideLink> tbl_GuideLink { get; set; }
        public virtual DbSet<tbl_EmailSettings> tbl_EmailSettings { get; set; }
    
        public virtual ObjectResult<sp_UserAccessPermissions_Result> sp_UserAccessPermissions(Nullable<int> roleId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UserAccessPermissions_Result>("sp_UserAccessPermissions", roleIdParameter);
        }
    
        public virtual ObjectResult<sp_AssignRoles_Result> sp_AssignRoles(Nullable<int> roleId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AssignRoles_Result>("sp_AssignRoles", roleIdParameter);
        }
    
        public virtual int SP_BaggegeCalculation(Nullable<long> quoteId)
        {
            var quoteIdParameter = quoteId.HasValue ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BaggegeCalculation", quoteIdParameter);
        }
    
        public virtual ObjectResult<SP_GetQuoteContents_Result> SP_GetQuoteContents(string fromCountryCode, string countryCode, string quoteType, Nullable<int> company)
        {
            var fromCountryCodeParameter = fromCountryCode != null ?
                new ObjectParameter("FromCountryCode", fromCountryCode) :
                new ObjectParameter("FromCountryCode", typeof(string));
    
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            var quoteTypeParameter = quoteType != null ?
                new ObjectParameter("QuoteType", quoteType) :
                new ObjectParameter("QuoteType", typeof(string));
    
            var companyParameter = company.HasValue ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetQuoteContents_Result>("SP_GetQuoteContents", fromCountryCodeParameter, countryCodeParameter, quoteTypeParameter, companyParameter);
        }
    
        public virtual ObjectResult<SP_GetBaggageXmlData_Result> SP_GetBaggageXmlData(Nullable<int> baggageQuoteId, Nullable<int> company)
        {
            var baggageQuoteIdParameter = baggageQuoteId.HasValue ?
                new ObjectParameter("BaggageQuoteId", baggageQuoteId) :
                new ObjectParameter("BaggageQuoteId", typeof(int));
    
            var companyParameter = company.HasValue ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetBaggageXmlData_Result>("SP_GetBaggageXmlData", baggageQuoteIdParameter, companyParameter);
        }
    
        public virtual ObjectResult<SP_GetCollectionDelivery_Result> SP_GetCollectionDelivery(Nullable<long> quoteId, Nullable<int> company)
        {
            var quoteIdParameter = quoteId.HasValue ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(long));
    
            var companyParameter = company.HasValue ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCollectionDelivery_Result>("SP_GetCollectionDelivery", quoteIdParameter, companyParameter);
        }
    
        public virtual ObjectResult<SP_GetXmlData_Result> SP_GetXmlData(Nullable<int> vehicleId)
        {
            var vehicleIdParameter = vehicleId.HasValue ?
                new ObjectParameter("VehicleId", vehicleId) :
                new ObjectParameter("VehicleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetXmlData_Result>("SP_GetXmlData", vehicleIdParameter);
        }
    
        public virtual ObjectResult<sp_GetdataForEmailSending_Result> sp_GetdataForEmailSending(Nullable<int> id, Nullable<int> value, string shippingType)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var valueParameter = value.HasValue ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(int));
    
            var shippingTypeParameter = shippingType != null ?
                new ObjectParameter("ShippingType", shippingType) :
                new ObjectParameter("ShippingType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetdataForEmailSending_Result>("sp_GetdataForEmailSending", idParameter, valueParameter, shippingTypeParameter);
        }
    
        public virtual ObjectResult<sp_GetAllHeadingContent_Result> sp_GetAllHeadingContent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllHeadingContent_Result>("sp_GetAllHeadingContent");
        }
    
        public virtual ObjectResult<sp_GetAllChildContent_Result> sp_GetAllChildContent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllChildContent_Result>("sp_GetAllChildContent");
        }
    
        public virtual int DeleteCourierRates(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCourierRates", companyIdParameter);
        }
    
        public virtual int DeleteExpressCourierRates(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteExpressCourierRates", companyIdParameter);
        }
    
        public virtual ObjectResult<SP_GetRemovalXmlData_Result> SP_GetRemovalXmlData(Nullable<long> quoteId)
        {
            var quoteIdParameter = quoteId.HasValue ?
                new ObjectParameter("QuoteId", quoteId) :
                new ObjectParameter("QuoteId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRemovalXmlData_Result>("SP_GetRemovalXmlData", quoteIdParameter);
        }
        public virtual ObjectResult<sp_GetVehicleAllListContent_Result> sp_GetVehicleAllListContent(Nullable<int> company, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var companyParameter = company.HasValue ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetVehicleAllListContent_Result>("sp_GetVehicleAllListContent", companyParameter, pageNumberParameter, pageSizeParameter);
        }

        public System.Data.Entity.DbSet<QuoteCalculatorAdmin.Models.DestinationDetails> DestinationDetails { get; set; }
    }
}
