//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class referrers
    {
        public long id { get; set; }
        public string name { get; set; }
        public string urlre { get; set; }
        public byte[] logo { get; set; }
        public string agenturl { get; set; }
        public string bccemail { get; set; }
        public System.DateTime lastupdate { get; set; }
    }
}
