//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public string port_code { get; set; }
        public string region1 { get; set; }
        public string country_def_port_grp { get; set; }
        public Nullable<int> country_klm_from_grp { get; set; }
    }
}
