//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class removal_services
    {
        public long id { get; set; }
        public string title { get; set; }
        public string surname { get; set; }
        public string forenames { get; set; }
        public string address { get; set; }
        public string telephone_home { get; set; }
        public string telephone_work { get; set; }
        public string fax_home { get; set; }
        public string fax_work { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public long country_id { get; set; }
        public string towncityregion { get; set; }
        public short full_household { get; set; }
        public short part_household { get; set; }
        public short selected_items { get; set; }
        public string vehicle { get; set; }
        public Nullable<int> storage_req_origin { get; set; }
        public Nullable<int> storage_req_destination { get; set; }
        public Nullable<System.DateTime> collection_date { get; set; }
        public string how_hear { get; set; }
        public string branch { get; set; }
        public short info_baggage_shipping { get; set; }
        public short info_banking_downunder { get; set; }
        public short info_car_shipping { get; set; }
        public short info_jobs_downunder { get; set; }
        public short info_overseas_property { get; set; }
        public short info_migrant_airfares { get; set; }
        public short info_money_transfers { get; set; }
        public short info_pet_transportation { get; set; }
        public short info_uk_tax_rebates { get; set; }
        public short info_pension_transfers { get; set; }
        public short info_offshore_investments { get; set; }
        public System.DateTime submission { get; set; }
        public Nullable<System.DateTime> followup_email_sent { get; set; }
    
        public virtual countries countries { get; set; }
    }
}
