//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class removals_inventory_document
    {
        public int id { get; set; }
        public string quote_request_id { get; set; }
        public string filename { get; set; }
        public string content_type { get; set; }
        public byte[] data { get; set; }
    }
}
