//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public review()
        {
            this.newsletter_category = new HashSet<newsletter_category>();
        }
    
        public long id { get; set; }
        public string title { get; set; }
        public string teaser { get; set; }
        public string article { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public short landing_page { get; set; }
        public decimal rating { get; set; }
        public long created_by_id { get; set; }
        public long last_modified_by_id { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public long version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newsletter_category> newsletter_category { get; set; }
    }
}
