//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class road_rates
    {
        public long id { get; set; }
        public long rates_destinations_id { get; set; }
        public decimal cost_3_cuft { get; set; }
        public decimal cost_6_cuft { get; set; }
        public decimal cost_9_cuft { get; set; }
        public decimal cost_12_cuft { get; set; }
        public decimal cost_15_cuft { get; set; }
        public decimal cost_18_cuft { get; set; }
        public decimal cost_21_cuft { get; set; }
        public decimal cost_24_cuft { get; set; }
        public decimal cost_27_cuft { get; set; }
        public decimal cost_30_cuft { get; set; }
        public decimal cost_33_cuft { get; set; }
        public decimal cost_36_cuft { get; set; }
        public decimal cost_39_cuft { get; set; }
        public decimal cost_42_cuft { get; set; }
        public decimal cost_45_cuft { get; set; }
        public decimal cost_68_cuft { get; set; }
        public decimal cost_90_cuft { get; set; }
        public decimal cost_100_cuft { get; set; }
        public Nullable<int> company { get; set; }
    }
}
