//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipments
    {
        public long id { get; set; }
        public string invnumber { get; set; }
        public string surname { get; set; }
        public string received { get; set; }
        public string vessel { get; set; }
        public string container { get; set; }
        public string destination { get; set; }
        public string eta { get; set; }
        public string agentname { get; set; }
        public string agentphone { get; set; }
        public string agentfax { get; set; }
        public string agentemail { get; set; }
        public string agentaddr1 { get; set; }
        public string agentaddr2 { get; set; }
        public string agentaddr3 { get; set; }
        public string agentaddr4 { get; set; }
        public System.DateTime lastupdate { get; set; }
    }
}
