//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class smailmge
    {
        public string name { get; set; }
        public Nullable<System.DateTime> last_ran { get; set; }
        public Nullable<short> fd_default { get; set; }
        public string filename { get; set; }
        public Nullable<long> f_enquiry { get; set; }
        public Nullable<long> t_enquiry { get; set; }
        public Nullable<System.DateTime> f_enq_dt { get; set; }
        public Nullable<System.DateTime> t_enq_dt { get; set; }
        public string ap_co { get; set; }
        public string estimator { get; set; }
        public Nullable<System.DateTime> f_est_dt { get; set; }
        public Nullable<System.DateTime> t_est_dt { get; set; }
        public Nullable<System.DateTime> f_move_dt { get; set; }
        public Nullable<System.DateTime> t_move_dt { get; set; }
        public string source { get; set; }
        public string region { get; set; }
        public string corp_cli { get; set; }
        public Nullable<System.DateTime> f_accept { get; set; }
        public Nullable<System.DateTime> t_accept { get; set; }
        public Nullable<short> accepted { get; set; }
        public Nullable<short> lost { get; set; }
        public string lost_to { get; set; }
        public string ap_no { get; set; }
        public Nullable<System.DateTime> f_quote_dt { get; set; }
        public Nullable<System.DateTime> t_quote_dt { get; set; }
        public string port { get; set; }
        public string wzone { get; set; }
        public string ship_type { get; set; }
        public string Branch { get; set; }
    }
}
