//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_message
    {
        public decimal id { get; set; }
        public decimal chat_id { get; set; }
        public string direction { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> sent { get; set; }
        public short send_fail { get; set; }
        public string send_fail_message { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime last_updated { get; set; }
    
        public virtual sms_chat sms_chat { get; set; }
    }
}
