//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_message_chat
    {
        public decimal id { get; set; }
        public string client_phone { get; set; }
        public string rep_phone { get; set; }
        public string company_id { get; set; }
        public string quote_type { get; set; }
        public string quote_id { get; set; }
        public string reply_email_address { get; set; }
        public short busy { get; set; }
        public short send_failed { get; set; }
        public string send_failed_message { get; set; }
        public short perm_fail { get; set; }
        public int resend_delay { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime last_updated { get; set; }
        public string version { get; set; }
    }
}
