//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_chat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sms_chat()
        {
            this.sms_message = new HashSet<sms_message>();
        }
    
        public decimal id { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string client_phone { get; set; }
        public string rep_phone { get; set; }
        public string company_id { get; set; }
        public string quote_type { get; set; }
        public string quote_id { get; set; }
        public string reply_email_address { get; set; }
        public string reference_url { get; set; }
        public short busy { get; set; }
        public short active { get; set; }
        public short @checked { get; set; }
        public short perm_fail { get; set; }
        public string perm_fail_message { get; set; }
        public int resend_delay { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime last_updated { get; set; }
        public string version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sms_message> sms_message { get; set; }
    }
}
