//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class static_resources
    {
        public long id { get; set; }
        public string site { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public byte[] data { get; set; }
        public System.DateTime last_updated { get; set; }
        public int version { get; set; }
    }
}
