//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BaggageItem
    {
        public long Id { get; set; }
        public long QuoteId { get; set; }
        public long CartonId { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public int Length { get; set; }
        public int Breadth { get; set; }
        public int Height { get; set; }
        public double Volume { get; set; }
        public Nullable<int> UserVolume { get; set; }
        public int Quantity { get; set; }
        public int Groweight { get; set; }
        public string MovewareDescription { get; set; }
        public Nullable<double> AirtFreightToAirport { get; set; }
        public Nullable<double> Courier { get; set; }
        public double SeaFreight { get; set; }
        public int Company { get; set; }
    }
}
