//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vehicle
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public int TitleId { get; set; }
        public string FromCountryName { get; set; }
        public string ToCountryCode { get; set; }
        public string PostCode { get; set; }
        public string CityName { get; set; }
        public System.DateTime EstimatedMoveDate { get; set; }
        public Nullable<int> VehicleType { get; set; }
        public string VehicleMakeName { get; set; }
        public string VehicleModelName { get; set; }
        public bool IsOwnedCar { get; set; }
        public string SpecialRequirement { get; set; }
        public bool IsConditionApply { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<double> FCL { get; set; }
        public Nullable<double> GPG { get; set; }
        public string QuoteNo { get; set; }
        public string EnquiryNo { get; set; }
        public Nullable<double> Volume_FCL { get; set; }
        public Nullable<double> Volume_GRP { get; set; }
        public Nullable<bool> IsFCL { get; set; }
        public Nullable<bool> IsGRP { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Company { get; set; }
        public string Sr_Code { get; set; }
        public string Sr_Name { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string AccessCode { get; set; }
    }
}
