//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccessCode
    {
        public long Id { get; set; }
        public string Email { get; set; }
        public string AccessCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int Company { get; set; }
    }
}
