//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuoteAmount
    {
        public int Id { get; set; }
        public int QuoteId { get; set; }
        public string MoveType { get; set; }
        public Nullable<decimal> QuoteAmount { get; set; }
        public string ShippingType { get; set; }
        public string ShippingTypeDescription { get; set; }
        public string TransitionTime { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsBooked { get; set; }
        public Nullable<long> CustomerReferenceNo { get; set; }
        public Nullable<int> CustomerQuoteNo { get; set; }
        public Nullable<int> QuoteSeqNo { get; set; }
        public Nullable<int> Company { get; set; }
    }
}
