//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Quote
    {
        public int EnquiryNo { get; set; }
        public string QuoteNo { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> MakeId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> TitleId { get; set; }
        public Nullable<System.DateTime> EstimatedMoveDate { get; set; }
        public Nullable<double> FCL { get; set; }
        public Nullable<double> GPG { get; set; }
    }
}
