//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VehicleShippingRates
    {
        public int Id { get; set; }
        public string CountryCode { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public bool FCL { get; set; }
        public bool GPG { get; set; }
        public Nullable<double> FCL_LON { get; set; }
        public Nullable<double> FCL_MCR { get; set; }
        public Nullable<double> FCL_GLA { get; set; }
        public Nullable<double> Groupage_Lon_PerMt { get; set; }
        public Nullable<double> Groupage_Lon_L_S { get; set; }
        public Nullable<double> Groupage_MCR_PerMt { get; set; }
        public Nullable<double> Groupage_MCR_L_S { get; set; }
        public Nullable<double> Groupage_GLA_PerMt { get; set; }
        public Nullable<double> Groupage_GLA_L_S { get; set; }
        public string TransitTimes_FCL { get; set; }
        public string TransitTimes_GRP { get; set; }
    }
}
