//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CreditorProducts
    {
        public long Id { get; set; }
        public string Branch { get; set; }
        public string CreditorProduct { get; set; }
        public Nullable<int> CreditorCode { get; set; }
        public string Method { get; set; }
        public string RemovalType { get; set; }
        public string Service { get; set; }
        public string IntType { get; set; }
        public string RateFixed { get; set; }
        public string OriginCode { get; set; }
        public string OriginRegion { get; set; }
        public string OriginDescriptionCity { get; set; }
        public string OriginState { get; set; }
        public string OriginCountry { get; set; }
        public string OriginDistance { get; set; }
        public string DestCode { get; set; }
        public string DestRegion { get; set; }
        public string DestDescriptionCity { get; set; }
        public string DestState { get; set; }
        public string DestCountry { get; set; }
        public Nullable<int> DestDistance { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<decimal> RateValue { get; set; }
        public Nullable<int> Margin { get; set; }
        public Nullable<decimal> MinimumCost { get; set; }
        public Nullable<decimal> MaximumCost { get; set; }
        public string TransitTimeshort { get; set; }
        public string TransitTimelong { get; set; }
        public string TransitType { get; set; }
        public Nullable<long> rateid { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Time { get; set; }
        public string Ratetype { get; set; }
        public Nullable<int> QtyMin { get; set; }
        public Nullable<int> QtyMax { get; set; }
        public string InternalComment { get; set; }
        public string LoadType { get; set; }
        public string CreditorProductStatus { get; set; }
    }
}
