//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uk
    {
        public string zip { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string a1 { get; set; }
        public string a2 { get; set; }
        public string state { get; set; }
    }
}
