//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_quotes
    {
        public int q_enquiry_no { get; set; }
        public int q_quote_no { get; set; }
        public System.DateTime q_quote_dt { get; set; }
        public string q_portcode { get; set; }
        public string q_type { get; set; }
        public string q_destcity { get; set; }
        public string q_radius { get; set; }
        public string q_volume { get; set; }
        public string q_amount { get; set; }
        public string q_weight { get; set; }
        public string q_tran_weeks { get; set; }
        public string q_tran_days { get; set; }
        public int q_air_rate { get; set; }
        public int q_air_volwt { get; set; }
        public int q_ins_car_value { get; set; }
        public decimal q_ins_car_pc { get; set; }
        public string q_car_type { get; set; }
        public string q_letter { get; set; }
        public short q_sendnexttime { get; set; }
        public string q_agent { get; set; }
        public string q_agentname { get; set; }
        public decimal q_sto_rate_f { get; set; }
        public decimal q_sto_hand_f { get; set; }
        public decimal q_sto_rate_g { get; set; }
        public decimal q_sto_hand_g { get; set; }
        public string q_ins_1 { get; set; }
        public string q_txt_1 { get; set; }
        public string q_ins_2 { get; set; }
        public string q_txt_2 { get; set; }
        public string q_ins_3 { get; set; }
        public string q_txt_3 { get; set; }
        public string q_ins_4 { get; set; }
        public string q_txt_4 { get; set; }
        public string q_ins_5 { get; set; }
        public string q_txt_5 { get; set; }
        public string q_ins_6 { get; set; }
        public string q_txt_6 { get; set; }
        public string q_ins_7 { get; set; }
        public string q_txt_7 { get; set; }
        public string q_ins_8 { get; set; }
        public string q_txt_8 { get; set; }
    
        public virtual vehicle vehicle { get; set; }
    }
}
