//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_model
    {
        public int id { get; set; }
        public int make_id { get; set; }
        public string name { get; set; }
        public Nullable<int> length_in_mm { get; set; }
        public Nullable<int> width_in_mm { get; set; }
        public Nullable<int> height_in_mm { get; set; }
        public Nullable<short> fits_in_container { get; set; }
        public Nullable<decimal> volume_in_cu_m { get; set; }
        public string vehicle_type { get; set; }
    }
}
