//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicle()
        {
            this.v_quotes = new HashSet<v_quotes>();
        }
    
        public int e_enquiry_no { get; set; }
        public Nullable<System.DateTime> e_enquiry_dt { get; set; }
        public string e_apcompany { get; set; }
        public string e_branch { get; set; }
        public string e_estimator { get; set; }
        public Nullable<System.DateTime> e_estim_dt { get; set; }
        public string e_estim_time { get; set; }
        public Nullable<System.DateTime> e_ship_dt { get; set; }
        public Nullable<System.DateTime> e_move_dt { get; set; }
        public string e_source { get; set; }
        public string e_comments { get; set; }
        public string e_surname { get; set; }
        public string e_title { get; set; }
        public string e_firstname { get; set; }
        public string e_initials { get; set; }
        public string e_salutation { get; set; }
        public string e_addr1 { get; set; }
        public string e_addr2 { get; set; }
        public string e_addr3 { get; set; }
        public string e_addr4 { get; set; }
        public string e_postcode { get; set; }
        public string e_region { get; set; }
        public string e_tel_home { get; set; }
        public string e_tel_work { get; set; }
        public string e_fax { get; set; }
        public string e_email { get; set; }
        public short e_emailq { get; set; }
        public string e_mobile { get; set; }
        public string e_company { get; set; }
        public string e_contact { get; set; }
        public string e_a_addr1 { get; set; }
        public string e_a_addr2 { get; set; }
        public string e_a_addr3 { get; set; }
        public string e_a_addr4 { get; set; }
        public string e_a_postcode { get; set; }
        public short e_lost { get; set; }
        public short e_accepted { get; set; }
        public string e_lost_to { get; set; }
        public string e_ap_number { get; set; }
        public Nullable<System.DateTime> e_adate { get; set; }
        public Nullable<System.DateTime> e_del_dt { get; set; }
        public string e_del_time { get; set; }
        public int e_a_quote_no { get; set; }
        public int e_h_quote_no { get; set; }
        public string e_notes { get; set; }
        public Nullable<System.DateTime> e_added { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_quotes> v_quotes { get; set; }
    }
}
