//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorPickfords.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch_postcode
    {
        public long id { get; set; }
        public long baggage_branch_id { get; set; }
        public string postcode { get; set; }
        public Nullable<short> dcr_zone { get; set; }
        public long removals_branch_id { get; set; }
        public long vehicle_branch_id { get; set; }
        public short removals_quotable { get; set; }
        public int CompanyId { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual branch branch1 { get; set; }
        public virtual branch branch2 { get; set; }
    }
}
