//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorPickfords.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartons
    {
        public long id { get; set; }
        public string type { get; set; }
        public short display { get; set; }
        public int displayorder { get; set; }
        public short standout { get; set; }
        public string description { get; set; }
        public string moveware_description { get; set; }
        public int length { get; set; }
        public int breadth { get; set; }
        public int height { get; set; }
        public int volume { get; set; }
        public int weight { get; set; }
        public string filter { get; set; }
        public string image { get; set; }
        public string title { get; set; }
    }
}
