//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorPickfords.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class matrix_c2c
    {
        public long id { get; set; }
        public int origin_zone_no { get; set; }
        public int destination_zone_no { get; set; }
        public string bag_zone_code { get; set; }
        public Nullable<int> company { get; set; }
    }
}
