//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorPickfords.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InternationalRemoval
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_InternationalRemoval()
        {
            this.tbl_AdditionalQuickQuoteItems = new HashSet<tbl_AdditionalQuickQuoteItems>();
        }
    
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string CountryCode { get; set; }
        public string Telephone { get; set; }
        public int TitleId { get; set; }
        public string FromCountryName { get; set; }
        public string ToCountryCode { get; set; }
        public string PostCode { get; set; }
        public string CityName { get; set; }
        public Nullable<System.DateTime> EstimatedMoveDate { get; set; }
        public Nullable<bool> IsConditionApply { get; set; }
        public Nullable<bool> HomeConsultationOrService { get; set; }
        public Nullable<bool> HomeVideoSurvery { get; set; }
        public Nullable<bool> QuickOnlineQuote { get; set; }
        public Nullable<System.DateTime> HomeConsultationDateTime { get; set; }
        public Nullable<int> BranchId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Company { get; set; }
        public string Sr_Code { get; set; }
        public string Sr_Name { get; set; }
        public Nullable<long> VideoSurveyId { get; set; }
        public Nullable<System.DateTime> VideoSurveyAppointmentTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AdditionalQuickQuoteItems> tbl_AdditionalQuickQuoteItems { get; set; }
    }
}
