//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorPickfords.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RemovalQuoteCalculaition
    {
        public int Id { get; set; }
        public int QuoteId { get; set; }
        public Nullable<decimal> Vehicle { get; set; }
        public Nullable<decimal> Labour { get; set; }
        public Nullable<decimal> ExcessMiles { get; set; }
        public Nullable<decimal> PackingMaterials { get; set; }
        public Nullable<decimal> SeaFreight { get; set; }
        public Nullable<decimal> ReceivingHandling { get; set; }
        public Nullable<decimal> DestinationCharges { get; set; }
        public Nullable<decimal> ChassisFee { get; set; }
        public Nullable<decimal> HHGDSISFFillingFee { get; set; }
        public Nullable<decimal> AMSCDF { get; set; }
        public Nullable<decimal> OriginCost { get; set; }
        public Nullable<decimal> OriginMarkup { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
