//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorPickfords.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChildContent
    {
        public int ChildContentId { get; set; }
        public Nullable<int> HeadingContentId { get; set; }
        public string ChildContent { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual tbl_HeadingContent tbl_HeadingContent { get; set; }
    }
}
