//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorPickfords.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RequestTracking
    {
        public int Id { get; set; }
        public string Vehicle { get; set; }
        public string Baggage { get; set; }
        public string InternationalRemoval { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsMailSend { get; set; }
    }
}
