//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteCalculatorAdmin.XmlService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:soap-fault:details")]
    public partial class FaultDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:openedgeservices:wsa1:mwservices")]
    public partial class mwgetfile_ttRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> ttidField;
        
        private string tttypeField;
        
        private string ttdataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> ttid {
            get {
                return this.ttidField;
            }
            set {
                this.ttidField = value;
                this.RaisePropertyChanged("ttid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string tttype {
            get {
                return this.tttypeField;
            }
            set {
                this.tttypeField = value;
                this.RaisePropertyChanged("tttype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ttdata {
            get {
                return this.ttdataField;
            }
            set {
                this.ttdataField = value;
                this.RaisePropertyChanged("ttdata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:openedgeservices:wsa1", ConfigurationName="XmlService.mwservicesObj")]
    public interface mwservicesObj {
        
        [System.ServiceModel.OperationContractAttribute(Action="mwsoap", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(QuoteCalculatorAdmin.XmlService.FaultDetail), Action="mwsoap", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QuoteCalculatorAdmin.XmlService.mwgetfileResponse mwgetfile(QuoteCalculatorAdmin.XmlService.mwgetfileRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="mwsoap", ReplyAction="*")]
        System.Threading.Tasks.Task<QuoteCalculatorAdmin.XmlService.mwgetfileResponse> mwgetfileAsync(QuoteCalculatorAdmin.XmlService.mwgetfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="mwsoap", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(QuoteCalculatorAdmin.XmlService.FaultDetail), Action="mwsoap", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QuoteCalculatorAdmin.XmlService.mwwebResponse mwweb(QuoteCalculatorAdmin.XmlService.mwwebRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="mwsoap", ReplyAction="*")]
        System.Threading.Tasks.Task<QuoteCalculatorAdmin.XmlService.mwwebResponse> mwwebAsync(QuoteCalculatorAdmin.XmlService.mwwebRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mwgetfile", WrapperNamespace="urn:openedgeservices:wsa1:mwservices", IsWrapped=true)]
    public partial class mwgetfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vddid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vKeyaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam4;
        
        public mwgetfileRequest() {
        }
        
        public mwgetfileRequest(string vUser, string vPass, string vddid, string vKeyaction, string pParam1, string pParam2, string pParam3, string pParam4) {
            this.vUser = vUser;
            this.vPass = vPass;
            this.vddid = vddid;
            this.vKeyaction = vKeyaction;
            this.pParam1 = pParam1;
            this.pParam2 = pParam2;
            this.pParam3 = pParam3;
            this.pParam4 = pParam4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mwgetfileResponse", WrapperNamespace="urn:openedgeservices:wsa1:mwservices", IsWrapped=true)]
    public partial class mwgetfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ttRow", IsNullable=false)]
        public QuoteCalculatorAdmin.XmlService.mwgetfile_ttRow[] tt;
        
        public mwgetfileResponse() {
        }
        
        public mwgetfileResponse(string result, QuoteCalculatorAdmin.XmlService.mwgetfile_ttRow[] tt) {
            this.result = result;
            this.tt = tt;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:openedgeservices:wsa1:mwservices")]
    public partial class mwweb_ttRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> tidField;
        
        private string ttableField;
        
        private string tstructureField;
        
        private string ttypeField;
        
        private string t1Field;
        
        private string t2Field;
        
        private string t3Field;
        
        private string t4Field;
        
        private string t5Field;
        
        private string t6Field;
        
        private string t7Field;
        
        private string t8Field;
        
        private string t9Field;
        
        private string t10Field;
        
        private string t11Field;
        
        private string t12Field;
        
        private string t13Field;
        
        private string t14Field;
        
        private string t15Field;
        
        private string t16Field;
        
        private string t17Field;
        
        private string t18Field;
        
        private string t19Field;
        
        private string t20Field;
        
        private string t21Field;
        
        private string t22Field;
        
        private string t23Field;
        
        private string t24Field;
        
        private string t25Field;
        
        private string t26Field;
        
        private string t27Field;
        
        private string t28Field;
        
        private string t29Field;
        
        private string t30Field;
        
        private string t31Field;
        
        private string t32Field;
        
        private string t33Field;
        
        private string t34Field;
        
        private string t35Field;
        
        private string t36Field;
        
        private string t37Field;
        
        private string t38Field;
        
        private string t39Field;
        
        private string t40Field;
        
        private string t41Field;
        
        private string t42Field;
        
        private string t43Field;
        
        private string t44Field;
        
        private string t45Field;
        
        private string t46Field;
        
        private string t47Field;
        
        private string t48Field;
        
        private string t49Field;
        
        private string t50Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
                this.RaisePropertyChanged("tid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ttable {
            get {
                return this.ttableField;
            }
            set {
                this.ttableField = value;
                this.RaisePropertyChanged("ttable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string tstructure {
            get {
                return this.tstructureField;
            }
            set {
                this.tstructureField = value;
                this.RaisePropertyChanged("tstructure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ttype {
            get {
                return this.ttypeField;
            }
            set {
                this.ttypeField = value;
                this.RaisePropertyChanged("ttype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string t1 {
            get {
                return this.t1Field;
            }
            set {
                this.t1Field = value;
                this.RaisePropertyChanged("t1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string t2 {
            get {
                return this.t2Field;
            }
            set {
                this.t2Field = value;
                this.RaisePropertyChanged("t2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string t3 {
            get {
                return this.t3Field;
            }
            set {
                this.t3Field = value;
                this.RaisePropertyChanged("t3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string t4 {
            get {
                return this.t4Field;
            }
            set {
                this.t4Field = value;
                this.RaisePropertyChanged("t4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string t5 {
            get {
                return this.t5Field;
            }
            set {
                this.t5Field = value;
                this.RaisePropertyChanged("t5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string t6 {
            get {
                return this.t6Field;
            }
            set {
                this.t6Field = value;
                this.RaisePropertyChanged("t6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string t7 {
            get {
                return this.t7Field;
            }
            set {
                this.t7Field = value;
                this.RaisePropertyChanged("t7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string t8 {
            get {
                return this.t8Field;
            }
            set {
                this.t8Field = value;
                this.RaisePropertyChanged("t8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string t9 {
            get {
                return this.t9Field;
            }
            set {
                this.t9Field = value;
                this.RaisePropertyChanged("t9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string t10 {
            get {
                return this.t10Field;
            }
            set {
                this.t10Field = value;
                this.RaisePropertyChanged("t10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string t11 {
            get {
                return this.t11Field;
            }
            set {
                this.t11Field = value;
                this.RaisePropertyChanged("t11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string t12 {
            get {
                return this.t12Field;
            }
            set {
                this.t12Field = value;
                this.RaisePropertyChanged("t12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string t13 {
            get {
                return this.t13Field;
            }
            set {
                this.t13Field = value;
                this.RaisePropertyChanged("t13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string t14 {
            get {
                return this.t14Field;
            }
            set {
                this.t14Field = value;
                this.RaisePropertyChanged("t14");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string t15 {
            get {
                return this.t15Field;
            }
            set {
                this.t15Field = value;
                this.RaisePropertyChanged("t15");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string t16 {
            get {
                return this.t16Field;
            }
            set {
                this.t16Field = value;
                this.RaisePropertyChanged("t16");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string t17 {
            get {
                return this.t17Field;
            }
            set {
                this.t17Field = value;
                this.RaisePropertyChanged("t17");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string t18 {
            get {
                return this.t18Field;
            }
            set {
                this.t18Field = value;
                this.RaisePropertyChanged("t18");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string t19 {
            get {
                return this.t19Field;
            }
            set {
                this.t19Field = value;
                this.RaisePropertyChanged("t19");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string t20 {
            get {
                return this.t20Field;
            }
            set {
                this.t20Field = value;
                this.RaisePropertyChanged("t20");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string t21 {
            get {
                return this.t21Field;
            }
            set {
                this.t21Field = value;
                this.RaisePropertyChanged("t21");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string t22 {
            get {
                return this.t22Field;
            }
            set {
                this.t22Field = value;
                this.RaisePropertyChanged("t22");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string t23 {
            get {
                return this.t23Field;
            }
            set {
                this.t23Field = value;
                this.RaisePropertyChanged("t23");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string t24 {
            get {
                return this.t24Field;
            }
            set {
                this.t24Field = value;
                this.RaisePropertyChanged("t24");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string t25 {
            get {
                return this.t25Field;
            }
            set {
                this.t25Field = value;
                this.RaisePropertyChanged("t25");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string t26 {
            get {
                return this.t26Field;
            }
            set {
                this.t26Field = value;
                this.RaisePropertyChanged("t26");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string t27 {
            get {
                return this.t27Field;
            }
            set {
                this.t27Field = value;
                this.RaisePropertyChanged("t27");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string t28 {
            get {
                return this.t28Field;
            }
            set {
                this.t28Field = value;
                this.RaisePropertyChanged("t28");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string t29 {
            get {
                return this.t29Field;
            }
            set {
                this.t29Field = value;
                this.RaisePropertyChanged("t29");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string t30 {
            get {
                return this.t30Field;
            }
            set {
                this.t30Field = value;
                this.RaisePropertyChanged("t30");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string t31 {
            get {
                return this.t31Field;
            }
            set {
                this.t31Field = value;
                this.RaisePropertyChanged("t31");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string t32 {
            get {
                return this.t32Field;
            }
            set {
                this.t32Field = value;
                this.RaisePropertyChanged("t32");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public string t33 {
            get {
                return this.t33Field;
            }
            set {
                this.t33Field = value;
                this.RaisePropertyChanged("t33");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public string t34 {
            get {
                return this.t34Field;
            }
            set {
                this.t34Field = value;
                this.RaisePropertyChanged("t34");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public string t35 {
            get {
                return this.t35Field;
            }
            set {
                this.t35Field = value;
                this.RaisePropertyChanged("t35");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public string t36 {
            get {
                return this.t36Field;
            }
            set {
                this.t36Field = value;
                this.RaisePropertyChanged("t36");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public string t37 {
            get {
                return this.t37Field;
            }
            set {
                this.t37Field = value;
                this.RaisePropertyChanged("t37");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public string t38 {
            get {
                return this.t38Field;
            }
            set {
                this.t38Field = value;
                this.RaisePropertyChanged("t38");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public string t39 {
            get {
                return this.t39Field;
            }
            set {
                this.t39Field = value;
                this.RaisePropertyChanged("t39");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public string t40 {
            get {
                return this.t40Field;
            }
            set {
                this.t40Field = value;
                this.RaisePropertyChanged("t40");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public string t41 {
            get {
                return this.t41Field;
            }
            set {
                this.t41Field = value;
                this.RaisePropertyChanged("t41");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public string t42 {
            get {
                return this.t42Field;
            }
            set {
                this.t42Field = value;
                this.RaisePropertyChanged("t42");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=46)]
        public string t43 {
            get {
                return this.t43Field;
            }
            set {
                this.t43Field = value;
                this.RaisePropertyChanged("t43");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=47)]
        public string t44 {
            get {
                return this.t44Field;
            }
            set {
                this.t44Field = value;
                this.RaisePropertyChanged("t44");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=48)]
        public string t45 {
            get {
                return this.t45Field;
            }
            set {
                this.t45Field = value;
                this.RaisePropertyChanged("t45");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public string t46 {
            get {
                return this.t46Field;
            }
            set {
                this.t46Field = value;
                this.RaisePropertyChanged("t46");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=50)]
        public string t47 {
            get {
                return this.t47Field;
            }
            set {
                this.t47Field = value;
                this.RaisePropertyChanged("t47");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=51)]
        public string t48 {
            get {
                return this.t48Field;
            }
            set {
                this.t48Field = value;
                this.RaisePropertyChanged("t48");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=52)]
        public string t49 {
            get {
                return this.t49Field;
            }
            set {
                this.t49Field = value;
                this.RaisePropertyChanged("t49");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=53)]
        public string t50 {
            get {
                return this.t50Field;
            }
            set {
                this.t50Field = value;
                this.RaisePropertyChanged("t50");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mwweb", WrapperNamespace="urn:openedgeservices:wsa1:mwservices", IsWrapped=true)]
    public partial class mwwebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pCall;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pRP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pWaybill;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pIQID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pCustCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pCredCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pAgentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pPage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pResults;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=18)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=19)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam9;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=20)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParam10;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=21)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ttRow", IsNullable=false)]
        public QuoteCalculatorAdmin.XmlService.mwweb_ttRow[] tt;
        
        public mwwebRequest() {
        }
        
        public mwwebRequest(
                    string pUser, 
                    string pPass, 
                    string pCall, 
                    string pRP, 
                    string pWaybill, 
                    string pIQID, 
                    string pCustCode, 
                    string pCredCode, 
                    string pAgentID, 
                    string pPage, 
                    string pResults, 
                    string pParam1, 
                    string pParam2, 
                    string pParam3, 
                    string pParam4, 
                    string pParam5, 
                    string pParam6, 
                    string pParam7, 
                    string pParam8, 
                    string pParam9, 
                    string pParam10, 
                    QuoteCalculatorAdmin.XmlService.mwweb_ttRow[] tt) {
            this.pUser = pUser;
            this.pPass = pPass;
            this.pCall = pCall;
            this.pRP = pRP;
            this.pWaybill = pWaybill;
            this.pIQID = pIQID;
            this.pCustCode = pCustCode;
            this.pCredCode = pCredCode;
            this.pAgentID = pAgentID;
            this.pPage = pPage;
            this.pResults = pResults;
            this.pParam1 = pParam1;
            this.pParam2 = pParam2;
            this.pParam3 = pParam3;
            this.pParam4 = pParam4;
            this.pParam5 = pParam5;
            this.pParam6 = pParam6;
            this.pParam7 = pParam7;
            this.pParam8 = pParam8;
            this.pParam9 = pParam9;
            this.pParam10 = pParam10;
            this.tt = tt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mwwebResponse", WrapperNamespace="urn:openedgeservices:wsa1:mwservices", IsWrapped=true)]
    public partial class mwwebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ttRow", IsNullable=false)]
        public QuoteCalculatorAdmin.XmlService.mwweb_ttRow[] tt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:openedgeservices:wsa1:mwservices", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pOK;
        
        public mwwebResponse() {
        }
        
        public mwwebResponse(string result, QuoteCalculatorAdmin.XmlService.mwweb_ttRow[] tt, string pOK) {
            this.result = result;
            this.tt = tt;
            this.pOK = pOK;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mwservicesObjChannel : QuoteCalculatorAdmin.XmlService.mwservicesObj, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mwservicesObjClient : System.ServiceModel.ClientBase<QuoteCalculatorAdmin.XmlService.mwservicesObj>, QuoteCalculatorAdmin.XmlService.mwservicesObj {
        
        public mwservicesObjClient() {
        }
        
        public mwservicesObjClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mwservicesObjClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mwservicesObjClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mwservicesObjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuoteCalculatorAdmin.XmlService.mwgetfileResponse QuoteCalculatorAdmin.XmlService.mwservicesObj.mwgetfile(QuoteCalculatorAdmin.XmlService.mwgetfileRequest request) {
            return base.Channel.mwgetfile(request);
        }
        
        public string mwgetfile(string vUser, string vPass, string vddid, string vKeyaction, string pParam1, string pParam2, string pParam3, string pParam4, out QuoteCalculatorAdmin.XmlService.mwgetfile_ttRow[] tt) {
            QuoteCalculatorAdmin.XmlService.mwgetfileRequest inValue = new QuoteCalculatorAdmin.XmlService.mwgetfileRequest();
            inValue.vUser = vUser;
            inValue.vPass = vPass;
            inValue.vddid = vddid;
            inValue.vKeyaction = vKeyaction;
            inValue.pParam1 = pParam1;
            inValue.pParam2 = pParam2;
            inValue.pParam3 = pParam3;
            inValue.pParam4 = pParam4;
            QuoteCalculatorAdmin.XmlService.mwgetfileResponse retVal = ((QuoteCalculatorAdmin.XmlService.mwservicesObj)(this)).mwgetfile(inValue);
            tt = retVal.tt;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<QuoteCalculatorAdmin.XmlService.mwgetfileResponse> mwgetfileAsync(QuoteCalculatorAdmin.XmlService.mwgetfileRequest request) {
            return base.Channel.mwgetfileAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuoteCalculatorAdmin.XmlService.mwwebResponse QuoteCalculatorAdmin.XmlService.mwservicesObj.mwweb(QuoteCalculatorAdmin.XmlService.mwwebRequest request) {
            return base.Channel.mwweb(request);
        }
        
        public string mwweb(
                    string pUser, 
                    string pPass, 
                    string pCall, 
                    string pRP, 
                    string pWaybill, 
                    string pIQID, 
                    string pCustCode, 
                    string pCredCode, 
                    string pAgentID, 
                    string pPage, 
                    string pResults, 
                    string pParam1, 
                    string pParam2, 
                    string pParam3, 
                    string pParam4, 
                    string pParam5, 
                    string pParam6, 
                    string pParam7, 
                    string pParam8, 
                    string pParam9, 
                    string pParam10, 
                    ref QuoteCalculatorAdmin.XmlService.mwweb_ttRow[] tt, 
                    out string pOK) {
            QuoteCalculatorAdmin.XmlService.mwwebRequest inValue = new QuoteCalculatorAdmin.XmlService.mwwebRequest();
            inValue.pUser = pUser;
            inValue.pPass = pPass;
            inValue.pCall = pCall;
            inValue.pRP = pRP;
            inValue.pWaybill = pWaybill;
            inValue.pIQID = pIQID;
            inValue.pCustCode = pCustCode;
            inValue.pCredCode = pCredCode;
            inValue.pAgentID = pAgentID;
            inValue.pPage = pPage;
            inValue.pResults = pResults;
            inValue.pParam1 = pParam1;
            inValue.pParam2 = pParam2;
            inValue.pParam3 = pParam3;
            inValue.pParam4 = pParam4;
            inValue.pParam5 = pParam5;
            inValue.pParam6 = pParam6;
            inValue.pParam7 = pParam7;
            inValue.pParam8 = pParam8;
            inValue.pParam9 = pParam9;
            inValue.pParam10 = pParam10;
            inValue.tt = tt;
            QuoteCalculatorAdmin.XmlService.mwwebResponse retVal = ((QuoteCalculatorAdmin.XmlService.mwservicesObj)(this)).mwweb(inValue);
            tt = retVal.tt;
            pOK = retVal.pOK;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<QuoteCalculatorAdmin.XmlService.mwwebResponse> mwwebAsync(QuoteCalculatorAdmin.XmlService.mwwebRequest request) {
            return base.Channel.mwwebAsync(request);
        }
    }
}
